-- ===========================================================================
-- sql_clientes_historial.sql — El historial de los clientes favoritos
--
-- Correr una vez en el SQL Editor de Supabase (proyecto de la Filtradora).
-- Es idempotente: repetirlo no toca nada que ya esté.
--
-- QUÉ PROBLEMA RESUELVE
--
-- El módulo «Clientes» arma su tabla cruzando por RUT lo que la app ya tiene
-- descargado: `public.compra_agil` y `public.licitaciones`. Eso es rápido y no
-- le pide nada al portal, pero tiene un agujero que ya estaba escrito en el
-- código: «lo que se pierde es lo que no esté en esas tablas: en Compra Ágil,
-- lo cerrado —la copia sólo guarda lo abierto—».
--
-- Y las dos tablas se vacían solas:
--
--   · `compra_agil` suelta cada noche lo que dejó de estar Publicada (cerró, se
--     adjudicó, se canceló o quedó desierta) y lo que sale de la ventana de 30
--     días;
--   · `licitaciones` se REEMPLAZA entera en cada descarga, así que lo que no
--     venga en la corrida de hoy desaparece.
--
-- Resultado: al vendedor que sigue a un comprador se le borraba el historial de
-- ese comprador cada noche. Lo que compró el mes pasado —justo lo que sirve
-- para saber qué le vas a vender el mes que viene— no quedaba en ninguna parte.
--
-- POR QUÉ EL HISTORIAL VIVE AQUÍ Y NO SE «DEJA DE BORRAR» EN LAS OTRAS
--
-- Porque en `licitaciones` no se puede: la tabla se reemplaza entera, y no
-- borrar una fila que sencillamente no viene en los datos nuevos exigiría
-- rehacer esa descarga de arriba abajo. Y porque `compra_agil` es la copia
-- COMPARTIDA con la que filtran todas las empresas: dejar dentro lo cerrado
-- para siempre la haría crecer sin tope y metería cotizaciones muertas en los
-- resultados de todo el mundo, que es lo contrario de lo que se pide.
--
-- Así que lo que se sigue es esto: antes de soltar una fila, si es de un
-- comprador que alguien sigue, se copia aquí con el estado al que pasó. La
-- fila deja las tablas de trabajo —que siguen ligeras— y el historial del
-- cliente no se pierde nunca.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- 1. La tabla
--
-- Puede existir ya: la creaba `sql_clientes.sql` cuando había un barrido propio
-- que iba al portal comprador por comprador. Ese barrido se quitó y la tabla
-- quedó dormida; esto la reaprovecha en vez de crear una tercera.
--
-- `empresa_id` va y se queda en NULL: lo que publica un organismo del Estado es
-- público e idéntico para todas las empresas, igual que `compra_agil`. Guardar
-- una copia por empresa sería multiplicar por N un dato que es el mismo.
-- ---------------------------------------------------------------------------
create table if not exists public.clientes_seguimiento (
  id                        bigint generated by default as identity primary key,
  empresa_id                uuid,
  rut_organismo             text not null,
  organismo                 text,
  -- 'compra_agil' | 'licitacion'. Las dos viven mezcladas y la pantalla las
  -- separa con este campo, que es como ya lo hacía el módulo.
  tipo                      text not null,
  numero_adquisicion        text not null,
  nombre_adquisicion        text,
  fecha_publicacion         text,
  fecha_cierre              text,
  fecha_cierre_1er_llamado  text,
  fecha_cierre_2do_llamado  text,
  llamado                   text,
  cantidad                  text,
  descripcion_producto      text,
  nombre_producto           text
);


-- ---------------------------------------------------------------------------
-- 2. La columna de Estado
--
-- Es la columna nueva, y va SÓLO aquí. En `compra_agil` no hace falta: esa
-- tabla guarda únicamente lo Publicada, así que una columna de estado diría
-- siempre lo mismo. Aquí sí, porque es lo único que distingue una cotización
-- que el cliente todavía puede responder de una que ya cerró hace tres meses.
--
-- Se guarda en minúsculas y tal como lo nombra el portal ('publicada',
-- 'cerrada', 'adjudicada', 'desierta', 'revocada'…). Es texto y no un enum a
-- propósito: el día que Mercado Público invente un estado nuevo, esto lo guarda
-- sin una migración de por medio; un enum obligaría a desplegar antes de poder
-- archivar, y lo que se perdería mientras tanto no se recupera.
--
-- `archivado_en` es cuándo lo vimos salir de lo publicado, no cuándo cerró: el
-- portal no dice lo segundo. Sirve para ordenar el historial y para saber, si
-- algún día cuadra mal, de qué barrido salió cada fila.
-- ---------------------------------------------------------------------------
alter table public.clientes_seguimiento
  add column if not exists estado text;

alter table public.clientes_seguimiento
  add column if not exists archivado_en timestamptz not null default now();

comment on column public.clientes_seguimiento.estado is
  'Estado en el portal al archivar: publicada | cerrada | adjudicada | desierta | '
  '... Minúsculas, tal como lo nombra Mercado Público.';

comment on column public.clientes_seguimiento.archivado_en is
  'Cuándo se vio salir de lo publicado. NO es la fecha de cierre: el portal no la da.';


-- ---------------------------------------------------------------------------
-- 3. Índices
--
-- El primero es el que usa la pantalla: «lo de estos RUT», que es la única
-- forma en que se lee esta tabla (nunca entera: dentro están los clientes de
-- todos los vendedores de todas las empresas).
--
-- El segundo es el que usa el barrido antes de archivar, para saber qué códigos
-- ya están guardados y no volver a insertarlos. Sin él, cada noche haría un
-- recorrido completo por cada lote de códigos.
-- ---------------------------------------------------------------------------
create index if not exists clientes_seguimiento_rut_tipo_idx
  on public.clientes_seguimiento (rut_organismo, tipo);

create index if not exists clientes_seguimiento_tipo_codigo_idx
  on public.clientes_seguimiento (tipo, numero_adquisicion);


-- ---------------------------------------------------------------------------
-- 4. Quién puede tocarla
--
-- Lee cualquiera que haya entrado (el contenido es público: son compras del
-- Estado, las mismas que ya están en `compra_agil`). Escribe sólo el barrido,
-- que entra con service_role y se salta RLS.
--
-- Las policies se crean sólo si faltan: `create policy` no admite
-- `if not exists`, así que se comprueba en el catálogo.
-- ---------------------------------------------------------------------------
alter table public.clientes_seguimiento enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename  = 'clientes_seguimiento'
       and policyname = 'clientes_seguimiento_lectura'
  ) then
    create policy clientes_seguimiento_lectura
      on public.clientes_seguimiento
      for select
      to authenticated
      using (true);
  end if;
end $$;

grant select on public.clientes_seguimiento to authenticated;
grant select, insert, update, delete on public.clientes_seguimiento to service_role;
grant usage, select on all sequences in schema public to service_role;


-- ---------------------------------------------------------------------------
-- 5. Que la API se entere
--
-- PostgREST cachea el esquema. Sin esto, la columna existe y la app recibe
-- «column clientes_seguimiento.estado does not exist» al leer.
-- ---------------------------------------------------------------------------
notify pgrst, 'reload schema';


-- ---------------------------------------------------------------------------
-- Comprobación
-- ---------------------------------------------------------------------------
select column_name, data_type, is_nullable
  from information_schema.columns
 where table_schema = 'public'
   and table_name = 'clientes_seguimiento'
 order by ordinal_position;
